### ISSUE TITLE
Create webhooks using an app without access to the webhook agent timeout

### ISSUE THREAD

**Issue by MargretheR** [SuperOffice/node-express-convert-certs-and-sys-token#10]
![image](https://user-images.githubusercontent.com/22498774/150354946-1e081e21-c4f2-44ab-9daf-88cac4b6ea40.png)

Include a description that this will happen if their app do not have access to this restricted agent

**Comment by SuperOfficeDevNet** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/15157161/154044171-5abb7c5e-9f47-4e38-98d0-b11e94b796b0.png)
