### ISSUE TITLE
User never gets logged in

### ISSUE THREAD

**Issue by camyyssa** [SuperOffice/node-express-convert-certs-and-sys-token#2]
## What is the issue
Running the app in localhost. After following the steps described in the Readme, I expect to end up in the signed in state. What actually happens is that after I go through the login flow in SuperOffice, I get redirected to the demo app on localhost, but I see the logged out state (with the Sign in button)

## Steps to reproduce
1. Click on the `Sign in` Button, fill in the SuperOffice sod client_id and client_secret and click `Sign in`
<img width="901" alt="Screen Shot 2020-11-23 at 16 30 31" src="https://user-images.githubusercontent.com/131612/99974254-58f36080-2da9-11eb-9a16-9578f211b4ea.png">

2. I get redirected to `sod.superoffice.com` where I successfully log in with my sod user

3. After successfully logging in, I get redirected as expected to the redirect url on localhost. 

4. The page looks like it did initially though. I'm not logged in.
<img width="995" alt="Screen Shot 2020-11-23 at 16 33 33" src="https://user-images.githubusercontent.com/131612/99974468-a66fcd80-2da9-11eb-885b-4ab5915875de.png">

What I could trace the issue back to is that the function defined in the `getStrategy` function never gets called: 
https://github.com/SuperOffice/node-express-convert-certs-and-sys-token/blob/35f2d03ef7a13375728eb5b19f12758a5c2ff390/controllers/authentication.js#L36-L42

## Notes
I don't have an SSL certificate installed locally, and this app seems to expect https access on localhost. I've modified the localhost URLs to use `http://` instead, but I don't know the consequences.

**Comment by AnthonyYates** [comment]
Hi @camyyssa , 

To get this to work locally in http, I changed:

https://github.com/SuperOffice/node-express-convert-certs-and-sys-token/blob/35f2d03ef7a13375728eb5b19f12758a5c2ff390/bin/www#L10

to

`var http = require('http');`

I changed:
https://github.com/SuperOffice/node-express-convert-certs-and-sys-token/blob/35f2d03ef7a13375728eb5b19f12758a5c2ff390/.env#L2

to (make sure this is allowed as a callback for your online application)

`OIDC_CALLBACK_URL=http://localhost:3300/openid/callback`

And also remove samesite:

https://github.com/SuperOffice/node-express-convert-certs-and-sys-token/blob/35f2d03ef7a13375728eb5b19f12758a5c2ff390/app.js#L53
